# This file defines the Kubernetes Service for the Syftbox application.
apiVersion: v1
kind: Service
metadata:
  name: syftbox
spec:
  selector:
    app: syftbox
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP