apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "syftbox-client.fullname" . }}-config
  labels:
    {{- include "syftbox-client.labels" . | nindent 4 }}
data:
  config.json: |
    {{- if .Values.client }}
    {{ .Values.client.config | toJson }}
    {{- else }}
    {}
    {{- end }}