{{- if and (eq .Values.deploymentType "statefulset") .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "syftbox-client.fullname" . }}-headless
  labels:
    {{- include "syftbox-client.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "syftbox-client.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.headlessService.port }}
    name: client
{{- end }}